app/urls.py
from django.urls import path
from app.views import *
app_name='something'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni')
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='nothing'
urlpatterns=[
    path('virat/',virat,name='virat')
]

project08/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS DHONI HTML PAGE</h1>
        <h1>THIS PAGE BELONGS TO APP</h1>
        <a href="{% url 'nothing:virat' %}">GO TO VIRAT PAGE</a>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS VIRAT HTML PAGE</h1>
        <h1>THIS PAGE BELONGS TO APP1</h1>
        <a href="{% url 'something:dhoni' %}">GO TO DHONI PAGE</a>
    </center>
</body>
</html>